### ISSUE TITLE
compute([])

### ISSUE THREAD

**Issue by andcastillo** [mljs/regression#10]
It would be useful to accept arrays as input for the compute method,  and loop it inside. 

var y = result.compute([1,2,3,4,5]); //result [2,4,6,8,10]

**Comment by targos** [comment]
Yep, it is on my todo list.

**Comment by lpatiny** [comment]
@andcastillo maybe you could take care of this ticket

**Comment by lpatiny** [comment]
Or in fact it is already implement and we can close this ticket ???

https://github.com/mljs/regression/blob/af49f0e2a8dc394cbfaf914fe7019800186581bb/src/regression/base-regression.js#L4-L18 ?

**Comment by andcastillo** [comment]
Closed by: 0d75d2c0fe116438d87f591c744340be86e33c70
